### ISSUE TITLE
Juice: If you can´t flip - camshake and sound

### ISSUE THREAD

**Issue by oscaroders** [oscaroders/TheTwilighitAdventures#101]

**Comment by oscaroders** [comment]
It works, It just don´t works!!!!!

**Comment by Knase23** [comment]
Borde fungera, fixade camera shake scriptet.
För att testa detta behöver man sätta Camera up och down. Kanske redan finns på dem med säkra att den finns.
Sen borde det finnas kod i Playerinput som ser till att när vi inte kan flippa och spelaren klickar på FlipWorld knappen så ska vi göra Camera shake. 
Så det borde vara bara att gå in i ett flipobjects med eve eller dodo, där den borde hamna. Och försöka flipa världen. Detta borde skaka BÅDA kamrerna.

**Comment by Karatesvennis** [comment]
Shake works well and as intended, but there's NO SOUND!
