### ISSUE TITLE
Game feel: Movment and Jump

### ISSUE THREAD

**Issue by oscaroders** [oscaroders/TheTwilighitAdventures#20]
Estimated Time: 10h

**Comment by Knase23** [comment]
Hittade en video som kanske vi kan ta hjälp av: [Better Jump in Unity with four lines of code (Youtube)](https://youtu.be/7KiK0Aqtmzc)

**Comment by fiolot** [comment]
Time to test move and jump values.

**Comment by fiolot** [comment]
How to test:
Check if it's too fast or too slow movement horizontaly and diagonally and airborne. 
Check if jump is too fast or to slow on the ascend and descend. 
Check if the player is airborne too long or too short.
