### ISSUE TITLE
Design : Puzzle System

### ISSUE THREAD

**Issue by Knase23** [oscaroders/TheTwilighitAdventures#30]
Need to structure up more, how it should be used when making levels. How the Class structure, and how it should be implemented

**Comment by fiolot** [comment]
Activator script:
Boolean
Array what to activate

How to change boolean scripts:
Lever script
Pressureplate script
Zone script
Crank script

Logic Gates:
AND
OR


Puzzle object abstract script:
virtual void OnActivation(Boolean)

	Sub scripts:
	Rotation
	Movement
	Open
	Dissapear
	

Physic object script
Box, you can push/pull it
