### ISSUE TITLE
Player Controller

### ISSUE THREAD

**Issue by Knase23** [oscaroders/TheTwilighitAdventures#5]
Uses somekind of inputManager to perform action the character can do. 
Example: Get the Jump button from Inputmanager and then call the jump function if it has the correct value.
Get the horizontal value from InputManager and pass it to Movement Function.
Restricts depending witch character you are. 

**Esstimated Time:** 2h

**Comment by Karatesvennis** [comment]
Ready regarding horizontal movement, awaiting jump script and whip functionality
