### ISSUE TITLE
Mechanic: Puzzle Action Movement

### ISSUE THREAD

**Issue by fiolot** [oscaroders/TheTwilighitAdventures#57]
On activation, move to another spot or move between two spots. 
Boolean for the two different function. 

**Requirement**
- #23

**Comment by fiolot** [comment]
Have problems with flip world. Movement updates the transform, but flip world doesn't update the trasnform.

**Comment by Karatesvennis** [comment]
Object can go from A to B on interaction with activator. Can also move back and forth. Possibly problems could arise when paired with flip world!?
