### ISSUE TITLE
Mechanic: Save/Load  to file

### ISSUE THREAD

**Issue by Knase23** [oscaroders/TheTwilighitAdventures#80]
Estimated Time: 10h

**Comment by Karatesvennis** [comment]
Made a save system(Json), but needs to be made more generic. Jesper said he was gonna perform a miracle..

**Comment by Karatesvennis** [comment]
Created an easier PlayerPrefs script for saving player and settings. Requires a lantern fuel amount for saving before it can be finished.

**Comment by Karatesvennis** [comment]
Updated Save() and Load() to include lanternFuel. Ready for testing, but still awaiting further settings (graphic, controller re-mapping) before finished.
