### ISSUE TITLE
Mechanic: Lantern

### ISSUE THREAD

**Issue by Knase23** [oscaroders/TheTwilighitAdventures#85]
Make it so when Eve walks over it/interact with it.  We can see Dodo. In the down world, with a some light around him. 

Rest of the down levels  should be black except for a small radius around Dodo. 

Estimated Time: 20h

**Comment by oscaroders** [comment]
There now is a SpriteMask called LanternLight in prefabs. and a DarknessLayers in prefabs. There also is a script called lanternControll witch can disable and change size on the light. But that has to be updated cause now it has its own update. witch is unnessesary.
