### ISSUE TITLE
Bug: Puzzlemovement player falls of the sideway moving platform

### ISSUE THREAD

**Issue by Flarne** [oscaroders/TheTwilighitAdventures#89]
When moving verticly player shaking up and down and falls of the platform when moving horizontaly.

**Comment by fiolot** [comment]
FixedJoint2D might solve the problem.

**Comment by fiolot** [comment]
How to test:
See if you can fall of the moving platform by standing on it.

**Comment by Karatesvennis** [comment]
Works well and as intended! DONE!
