### ISSUE TITLE
Research: Look for sounds for jump, ambient jungle sounds other sound effects/ music

### ISSUE THREAD

**Issue by Knase23** [oscaroders/TheTwilighitAdventures#91]

**Comment by Flarne** [comment]
[https://iamzone.itch.io/day2](https://iamzone.itch.io/day2)

**Comment by Flarne** [comment]
[https://soundcloud.com/surt_r/temple?in=surt_r/sets/devil-tower-rpg-sound](https://soundcloud.com/surt_r/temple?in=surt_r/sets/devil-tower-rpg-sound)

**Comment by Flarne** [comment]
[https://soundcloud.com/abstraction/ludum-dare-32-fifth-track?in=abstraction/sets/ludum-dare-challenge](https://soundcloud.com/abstraction/ludum-dare-32-fifth-track?in=abstraction/sets/ludum-dare-challenge)

**Comment by Flarne** [comment]
I have Searched for ambient sound And made some jump sound

**Comment by Flarne** [comment]
oops

**Comment by Flarne** [comment]
Searched for Ambient sound and sound effects, and fixed functions in code to get it to work.
